import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '../styles/globals.css';
import TailFooter from '@/components/objects/footer/TailFooter';
import SideNav from '@/components/objects/sideNavigation/sideNavigation';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <head>
                <meta charSet="utf-8" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <meta name="description" />
                <title>TU Library Management</title>
            </head>
            <body className={inter.className}>
                <header></header>
                <main className={`w-screen h-[95dvh] bg-white text-black`}>
                    <div className='h-full w-full sm:w-[350px]'>
                        <SideNav />
                    </div>
                    {children}
                </main>
                <footer className="h-[5dvh]">
                    <TailFooter />
                </footer>
            </body>
        </html>
    );
}
